### PR TITLE
Remove support for Python 3.2

### LINKED ISSUE #73: End Python 3.2 support (must cut a release + modify changelog)
Python 3.2's flake and mypy malfunction. This makes our build process and imports somewhat nasty (introduced in https://github.com/goavki/apertium-apy/pull/69).

Should we stop supporting Py3.2?

cc @unhammer

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #73

### CODE REVIEW

**Comment by Androbin** [comment]
@sushain97 What do we need to add to `Changelog` and `NEWS` ?

**Comment by sushain97** [comment]
If I knew, I would do it :) you'll have to look through commits since the
last tag to figure it out

**Comment by Androbin** [comment]
Well, that was nasty. Is the syntax and everything okay?

**Comment by sushain97** [comment]
@unhammer should we bump to v1.0.0? it seems too early.

probably v0.10.0 as earliest version not supporting Py3.2 makes more sense?

**Comment by Androbin** [comment]
> Also, perhaps Apy is **feature-complete enough** that we could make a release now, calling it The last one supporting 3.2, bump a **major version number** and from then on only support 3.3 and higher.

@unhammer already suggested doing so.

**Comment by sushain97** [comment]
The transition to v1.0.0 is pretty big. I'd like to confirm.

**Comment by unhammer** [comment]
> probably v0.10.0 as earliest version not supporting Py3.2 makes more sense?

+1, let's wait with 1.0 until all these changes have been in production for a while

**Comment by Androbin** [comment]
Okay, I have modified the last commit accordingly.

**Comment by sushain97** [comment]
@unhammer In that case, should we release v0.9.2 with all the new changes and then v0.10.0 with just Python 3.2 support being gone? It would give people on Python 3.2 the new changes between v0.9.1 and v0.9.2 but if there are any bugs we'd have to make a branch and release v0.9.3 (meh). Other option is to just make v0.10.0 also have all the new changes since v0.9.1.

**Comment by Androbin** [comment]
Maybe @TinoDidriksen can tell how much the support is needed.

**Comment by TinoDidriksen** [comment]
I see no reason to support Python 3.2. The supported platforms that have Python 3 have version 3.4+, and the rest don't have Python 3 at all so people will install latest version themselves.

**Comment by Androbin** [comment]
@sushain97 Are we good to go then?

**Comment by unhammer** [comment]
Yeah, I think we can go with whatever option is easiest …

**Pull request merged**
