### PR TITLE
Add suggestions route and wiki api functionality

### PR DESCRIPTION
**Pull request by svineet**
As part of [this](https://codein.withgoogle.com/dashboard/task-instances/6076012865519616/?sp-page=1) task.

See [http://wiki.apertium.org/wiki/User:Svineet](http://wiki.apertium.org/wiki/User:Svineet) for the format data is recorded in (currently).

### CODE REVIEW

**Comment by jonorthwash** [comment]
Test comment.

**Comment by sushain97** [comment]
Move addSuggestion back into `util.py` since it isn't specifically wiki-only.

**Comment by ftyers** [comment]
The format looks ok, but it should use a template. http://wiki.apertium.org/wiki/Template:Suggest

**Comment by svineet** [comment]
@ftyers yeah there's a config option for which page suggestions should be sent to so no worries there.

**Comment by svineet** [comment]
ehm, forgive my ignorance, I now understand what the Template is about. Hopefully ready for merge now :smile: 

I will start work on ReCAPTCHA meanwhile.

**Comment by svineet** [comment]
OK, so we have to shift the functionality to GET, because jsonp does not support POST. I am going to make the change now, if you guys know of any workaround for making POST work or a reason why GET should be avoided (any security reasons?), please do list it down here.

**Comment by sushain97** [comment]
Regarding GET, we could use CORS. Doesn't APY already support CORS?

**Comment by svineet** [comment]
Let's work on merging this! What should the default page be for recording suggestions?

**Comment by jonorthwash** [comment]
What's the status of this?  We have a GSoC project this year that will include suggestion stuff...  Would it be worth the student's while to try to merge this in?

**Comment by svineet** [comment]
The UI might need more refinement (I think we had a discussion long ago on IRC, I'll look for it), but the API endpoints are fine IMHO. Yeah let's go ahead with trying to merge this, what do you say?

Ah I see I forgot to jot it down here, the code now uses CORS.

**Comment by jonorthwash** [comment]
Yeah, let's do it.  @Kira-D can help with it as part of her GSoC project.  What needs to be done?

**Comment by Kira-D** [comment]
@jonorthwash, @svineet, I've played with local copies and found out that there is only one conflict.
http://pastebin.com/49ADizp3
The new arguments that related to the suggestion task were added.

**Comment by jonorthwash** [comment]
In that case, it looks like an easy merge.  @svineet, you should be able to modify that aspect of this pull request pretty easily so we can merge the code in.

**Comment by svineet** [comment]
Not sure why the check is failing :(

**Comment by jonorthwash** [comment]
Is it because it thinks `-z` is an argument to another switch?

`    FileNotFoundError: [Errno 2] No such file or directory: '-z'`

**Comment by unhammer** [comment]
@svineet, see t/README on how to get the data to run the tests

**Comment by unhammer** [comment]
Actually, scratch that; I'm getting a failure on master as well. Something up with the language data I guess.

**Comment by unhammer** [comment]
Svinieet, merge goavki/master and push again

**Comment by jonorthwash** [comment]
Looks mergeable now (tests passing).  Should we do it?

**Comment by jonorthwash** [comment]
New branch has been made for this code: https://github.com/goavki/apertium-apy/tree/suggestions

**Comment by svineet** [comment]
Redirecting PR to the new branch

**Pull request closed without merging**
